export icons from "./icons8-instagram-48.png"
export arrow_back from "./arrow_back_ios_24px.png"
export close from "./close.png"
export dino from "./dino pattern-01 1.png"
export eggs from "./eggs.png"
export elipse from "./Ellipse 6.png"
export free_icon from "./free-icon-close-3943324.png"
export girrafe from "./giraffe.png"
export one_earth from "./one earth-01 1.png"
export paket from "./paket 1 (1).png"
export rectangle from "./Rectangle 62.png"
export reuse_bag from "./reuse bag_Монтажная область 1 1.png"
export right from "./right.png"
export van_01 from "./van-01 1.png"
export vsem_torba_circle from "./vsem torba круг.png"
export vsem_torba_toward from "./vsem torba прямой.png"
export cow from "./коровка-01 1.png"

